export const SEARCH_VALUE_INPUTTED = 'SEARCH_VALUE_INPUTTED';
export const USER_IS_SEARCHING = 'USER_IS_SEARCHING';
export const BACKSPACE_OCCURED= 'BACKSPACE_OCCURED';
export const SEARCH_STATUS_UPDATE='SEARCH_STATUS_UPDATE';


export const STORE_IDS_FROM_SEVER = 'STORE_IDS_FROM_SEVER';